### ISSUE TITLE
Keeps saying corrupt file when trying to open my file

### ISSUE THREAD

**Issue by cellus2323** [akeaswaran/cfc-bugs#127] opened 2021-04-01 05:19 UTC
Please fill out the template below to make sure I can assist you most effectively.

**Describe 
When I try opening up my file to continue my career, an error keeps coming up telling me to delete the file. Buh I’ve had the file for 18 seasons and would be devastated if I have to delete it. 

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on 
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc. iPhone X
**Jailbroken**: Whether or not your device is jailbroken. NO
**Reproducible:** Can you reproduce it every time? Or is it random?
EVERYTIME

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.
![32058AFC-1855-405B-BF9F-D3FB54158C22](https://user-images.githubusercontent.com/81733998/113247099-24b81100-926f-11eb-970b-11886a991891.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**
Please fix it. I love this game

**Comment by akeaswaran** [comment] 2021-04-01 13:25
Did this start happening consistently after you took a specific action in this specific save file? I have a guess at a root cause, but I want to confirm.

**Comment by cellus2323** [comment] 2021-04-01 15:01
I do not know. It’s just started happening when I closed the app and tried to open the file a few hours later.

**Comment by cellus2323** [comment] 2021-04-03 03:06
> Did this start happening consistently after you took a specific action in this specific save file? I have a guess at a root cause, but I want to confirm.

So is there anything that you can do?

**Comment by akeaswaran** [comment] 2021-04-03 03:43
This issue should be fixed in future seasons in v5.0.1. However, I'm not sure if I can fix your save file from being in a bad state -- the save file corruption alert isn't a false positive. If you really, really, really want to keep this save file, please hold off on using it for now. I'll work on a solution in 5.0.2 and will provide an update if I can figure something out.

**Comment by akeaswaran** [comment] 2021-04-05 23:26
5.0.2 is currently in review and should fix this issue when it rolls out. Please be on the lookout for that update over the next few days, and let me know if it solves the issue.

**Closed by akeaswaran** 2021-04-05 23:26 UTC
Labels: bug
