### ISSUE TITLE
I think you should make it where you can change the player names and also number 

### ISSUE THREAD

**Issue by Tylet123** [akeaswaran/cfc-bugs#53] opened 2020-09-25 19:25 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tylet123** [comment] 2020-09-25 19:26
I think we should be able to change player names and number

**Comment by akeaswaran** [comment] 2020-09-25 20:22
Duplicate of #19. Closing.

**Closed by akeaswaran** 2020-09-25 20:22 UTC
Labels: enhancement
