### ISSUE TITLE
There as an issue with corrupt file

### ISSUE THREAD

**Issue by nateumbar** [akeaswaran/cfc-bugs#158] opened 2021-06-19 11:24 UTC
For some reason whenever I leave a game I get kicked out when trying to join back and it claims there is a corrupt file this happens consistently.

**Comment by akeaswaran** [comment] 2021-06-19 16:14
Duplicate of #152, closing.

This is a known issue that I am actively working on; I hope to have an update that fixes things out on the App Store soon.

**Closed as completed by akeaswaran** 2021-06-19 16:14 UTC
Labels: bug
