### ISSUE TITLE
Spread offense 

### ISSUE THREAD

**Issue by jimmy17397** [akeaswaran/cfc-bugs#135] opened 2021-04-17 20:02 UTC
**Is your feature request related to a problem? Please describe.**
The spread offense doesn’t use the TE even tho the TE is a massive part of spread offense’s in actual college football

**Describe the solution you'd like**
Allow the use of a TE enstead of having 4WR use 3WR and 1TE

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment] 2021-04-21 04:29
More or less a duplicate of #9, closing.

**Closed by akeaswaran** 2021-04-21 04:29 UTC
Labels: enhancement
