### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by alexanderk02** [akeaswaran/cfc-bugs#148] opened 2021-05-15 00:57 UTC
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

My last two save files on CFC have both become corrupt and I can’t use them anymore.

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (School/Normal)
- Difficulty (Hard)
- Manage Coaching Staff (On)
- Promotion/Relegation (On)
- Automated Recruiting (Off)

**Reproducible:** Can you reproduce it every time? Or is it random?
Every time
**Expected behavior**
For me to be able to use the save file

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment] 2021-05-15 16:37
Duplicate of #142, closing.

**Closed as completed by akeaswaran** 2021-05-15 16:37 UTC
Labels: bug
