### ISSUE TITLE
Keep getting corrupt save file

### ISSUE THREAD

**Issue by tbird320** [akeaswaran/cfc-bugs#147] opened 2021-05-11 23:11 UTC
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment] 2021-05-12 01:02
Duplicate of #142, closing.

**Closed as completed by akeaswaran** 2021-05-12 01:02 UTC
Labels: bug
