### ISSUE TITLE
Subs

### ISSUE THREAD

**Issue by tyrpar** [akeaswaran/cfc-bugs#58] opened 2020-10-19 04:21 UTC
I don’t have any problems. I just think that you should allow us to sub people in and out of games. So if I’m up by 40 in the 4th I can give my backup QB playing time. I think this would be really cool

**Comment by akeaswaran** [comment] 2020-10-19 19:48
Duplicate of #17. See that issue for more info.

**Closed by akeaswaran** 2020-10-19 19:48 UTC
Labels: enhancement
