### ISSUE TITLE
Recruiting Points miscalculated AND High expectations when switching to low-prestige school

### ISSUE THREAD

**Issue by gottem11111** [akeaswaran/cfc-bugs#25] opened 2020-07-06 20:04 UTC
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
If you change school from a high prestige one to a low prestige school, the first year you spend the same recruiting points as if you still were on the high prestige school. Everything is normal when you go in to the second recruitment period after the first season with the new school. 

Another thing I noticed is that expectations are pretty high when you were successful (winning a couple of natties) and you go to an unsuccessful school (for example 4 wins in 2 years). The media still expects your school to be in the middle of the conference even if you have low 70s in offense and Defense. Of course you fail to meet those expectations in the first year. 

**To Reproduce**

**iOS version**: 13 
**CFC version**: newest on App Store 
**iOS device**: 8
**Jailbroken**: no
**Reproducible:** yes

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment] 2020-07-07 00:38
> If you change school from a high prestige one to a low prestige school, the first year you spend the same recruiting points as if you still were on the high prestige school. Everything is normal when you go in to the second recruitment period after the first season with the new school.

Took a look at this part of your ticket -- think I have a fix for that, will ship in the next update! 

As for the other part, will update this if I'm able to reproduce it.

**Comment by akeaswaran** [comment] 2020-07-09 17:32
Hm, not able to reproduce the other part of this ticket on my end. Closing this for now, but if you see it again, let me know.

**Closed by akeaswaran** 2020-07-09 17:32 UTC
Labels: bug, under investigation
