### ISSUE TITLE
Passing Yards Leader list is bugged, showing incorrect stats

### ISSUE THREAD

**Issue by etns23** [akeaswaran/cfc-bugs#121] opened 2021-02-09 06:57 UTC
**Describe the bug**
Through 3 weeks into my season, the passing yards leader on the list has stats showing 6 games played in only 3 weeks and 6 games worth of yards.

**To Reproduce**
1. Sim through 2-3 weeks
2. Go to Passing Yards Leaders

**iOS version**: iOS 14.4
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: iPhone 11
**Jailbroken**: No
**Reproducible:** Not sure, most likely random since it has never happened before.

**Expected behavior**
I expected the list to show accurate stats based on every player playing the correct amount of games.

**Screenshots**
![8A57737C-5E4D-4D03-B502-F3A5C857FD03](https://user-images.githubusercontent.com/70407573/107326838-1d983200-6a7a-11eb-9252-212bd8ab66fd.png)
![7A0A8512-7416-4A82-AF76-E3510C20B43E](https://user-images.githubusercontent.com/70407573/107326840-1d983200-6a7a-11eb-94f8-ded08f112d6d.png)
![CCA62B03-80A4-49F4-A4F3-8E36C05EB5F6](https://user-images.githubusercontent.com/70407573/107326842-1d983200-6a7a-11eb-9d29-f6da91e06a10.png)

**Additional context**
This has never happened to me before, and I'm not sure if it will happen again.

**Comment by akeaswaran** [comment] 2021-02-09 07:02
Gotta say -- never seen a player be duplicated before. I wonder if he's on two different teams but his information hasn't been updated properly. 

I'll look into this when I get the chance, but I do think you're right in that this may be effectively random. If you can reproduce this via the transfer portal, please let me know.

**Comment by etns23** [comment] 2021-02-09 08:39
So, it seems since there are 2 of this guy that he gets double stats. Through week 4 and he has 8 games played. Could possibly mess with awards and such.

**Comment by etns23** [comment] 2021-02-09 08:40
Also, they aren't listed twice in the NYS roster just as their starter.

**Comment by akeaswaran** [comment] 2021-02-09 22:56
Is the player listed on another team's roster? I realize that this isn't easy to check, but I get the feeling he may be, which is why he's showing up for two teams.

**Comment by etns23** [comment] 2021-02-09 23:01
Did some digging, the player is listed as starting for both Boston State and New York State. Pictures are their qb depth charts.
![1FA7A761-6D63-4973-B638-9CB7B88000C1](https://user-images.githubusercontent.com/70407573/107439875-c25d5280-6b00-11eb-96f2-8e4e0dd9a86c.jpeg)
![414B2C3D-101B-44A5-B0D2-352AC3426A41](https://user-images.githubusercontent.com/70407573/107439878-c25d5280-6b00-11eb-8578-fb39ab78de13.jpeg)

**Comment by akeaswaran** [comment] 2021-02-11 03:04
Noted. I figure this is because the player was not removed properly from his original team via the transfer portal. I think I have a fix for this in a future release.

**Closed by akeaswaran** 2021-02-11 03:04 UTC
Labels: bug
