### ISSUE TITLE
Game files corrupt everytime I create a new save file and rename all the conferences and teams

### ISSUE THREAD

**Issue by gatorfan1** [akeaswaran/cfc-bugs#154] opened 2021-06-08 19:28 UTC
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

my save file corrupts everytime I start a new save file and make changes to the teams and conferences, it will allow 1-2 seasons to be played and then it will promptly corrupt at the start of the second or third season. I have had this happen 4 times in the last 24 hours. 

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

I have been playing on a non jailbroken iPhone 12 Pro, and using career mode with Hard difficulty, managing staff on with promotion/relegation on and with manual recruiting on. 

**Reproducible:** Can you reproduce it every time? Or is it random?

it happens everytime I rename conferences and teams with the above settings. 

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment] 2021-06-08 20:52
Duplicate of #152, closing.

I'm actively working on this issue.

**Closed as completed by akeaswaran** 2021-06-08 20:52 UTC
Labels: bug
