### ISSUE TITLE
Extra Feature

### ISSUE THREAD

**Issue by Kobie-2** [akeaswaran/cfc-bugs#65] opened 2020-10-27 02:02 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

I was just thinking, since you guys have done a great job with the app and just updated the app to having offensive coordinators and defensive coordinators, maybe make it an option for us to only be one of those. Start out as an offensive coordinator, defensive coordinator, or head coach all as a choice at the beginning of the game. 

**Additional context**

**Comment by akeaswaran** [comment] 2020-11-02 23:59
Duplicate of #69 -- I'm not planning on supporting a coordinator mode at this time. However, if there's enough interest for that in our community (like on /r/FootballCoach, then I can explore building it out.

**Closed by akeaswaran** 2020-11-02 23:59 UTC
Labels: enhancement
