### ISSUE TITLE
Game save files keep corrupting 

### ISSUE THREAD

**Issue by NightSpoon** [akeaswaran/cfc-bugs#159] opened 2021-06-19 21:40 UTC
Please fill out the template below to make sure I can assist you most effectively 

**Describe the bug**

Every time I try and reload my most recent save file on school mode. Coach manual. No In season scout. It says my save file has become corrupted. iOS on iPhone 12. It has happen to me 3 times at this point

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment] 2021-06-19 22:00
Duplicate of #152. I am aware of this issue and I am actively working on it. I hope to have a fix for the issue up on the App Store soon.

**Closed as completed by akeaswaran** 2021-06-19 22:00 UTC
Labels: bug

**Comment by NightSpoon** [comment] 2021-06-19 22:32
Ah perfect. Thank you. I’ve been playing your game for probably almost a
year or two it feels like now. Always been one of my favorite. Keep that
good shit up
