### ISSUE TITLE
Edit Players

### ISSUE THREAD

**Issue by Malik-hue** [akeaswaran/cfc-bugs#54] opened 2020-09-28 01:39 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Malik-hue** [comment] 2020-09-28 01:40
Allow us to edit players but not gain Achievements

**Comment by akeaswaran** [comment] 2020-09-28 03:37
Duplicate of #19, closing.

**Closed by akeaswaran** 2020-09-28 03:37 UTC
Labels: enhancement
