### ISSUE TITLE
I think it would be nice if we could fire and hire offensive and defensive coordinators during the regular and off season, instead of just the off season. 

### ISSUE THREAD

**Issue by CuddlyV77** [akeaswaran/cfc-bugs#193] opened 2021-10-31 04:25 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment] 2021-10-31 12:25
Duplicate of #194. Closing.

**Closed as completed** 2021-10-31 12:25 UTC
Labels: enhancement, wontfix
